#!/usr/bin/bash

if [ ! -d "./microdosimetry-build" ]; then
  mkdir microdosimetry-build
fi
cd microdosimetry-build

cmake -DGeant4_DIR= /home/dthompson/geant4-v.11.1.1-install/lib/Geant11.1.1 ../ 

make
